# Generated by Django 4.2.15 on 2024-10-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category  ', 'verbose_name_plural': 'categories '},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_time'], 'verbose_name': 'new  ', 'verbose_name_plural': 'news '},
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/images/1.jpg', upload_to='news/images/'),
        ),
    ]
